syntax on

call plug#begin('~/.vim/plugged')
  Plug 'itchyny/lightline.vim'
  Plug 'https://github.com/romainl/vim-cool'
  Plug 'https://github.com/tpope/vim-commentary'
  Plug 'https://github.com/tpope/vim-surround'
  Plug 'francoiscabrol/ranger.vim'
  Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
  Plug 'junegunn/fzf.vim'
  Plug 'tpope/vim-fugitive'
  Plug 'https://github.com/airblade/vim-gitgutter'
  Plug 'flrnprz/plastic.vim'
call plug#end()

colorscheme plastic
let g:lightline = { 'colorscheme': 'plastic' }

" SETS
set undofile
set undodir=$TEMP

set autochdir
set autoindent
set completeopt=longest,menuone
set fenc=utf-8
set fileencodings=utf-8,latin2
set gdefault
set hidden
set ignorecase
set incsearch
set laststatus=2
set mouse=a
set nobackup
set nocompatible
set noexpandtab
set foldmethod=indent
set nofoldenable
set nowrap
set nowritebackup
set relativenumber number
set ruler
set showcmd
set t_Co=256
set tabpagemax=50
set wildmenu
set wrapscan
set clipboard+=autoselect
set background=dark
set shiftwidth=4
set softtabstop=4
set tabstop=4
set expandtab
set guioptions=agrLTi

"Leader
let mapleader = " "

"FUNCTIONS
command! DosToUnix %s/\r//g
command! Q q
command! W w
command! RmEmptyLines g/^$/d
cnoremap w!! %!sudo tee > /dev/null

fun s:TabsToSpaces()
    set expandtab ts=4 sw=4 ai
    %retab
endf
command! TabsToSpaces call s:TabsToSpaces()


"MOUSE
set mouse+=a
if &term =~ '^screen'
    set ttymouse=xterm2
endif

"Plugins
let g:ranger_command_override = 'ranger --cmd "set show_hidden=true"'
let g:fzf_buffers_jump = 1

