export ZSH="$HOME/.oh-my-zsh"
export KEYTIMEOUT=1
ENABLE_CORRECTION="true"
ZSH_THEME="jreese"
CASE_SENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
HIST_STAMPS="yyyy/mm/dd"
DISABLE_UNTRACKED_FILES_DIRTY="true"
plugins=(
  # brew
  autojump
  cp
  # django
  git
  # git-flow
  gitignore
  pip
  tmux
  # zsh-nvm
  # vim-inteaction
)

load () { [ -f "$1" ] && source $1 > /dev/null}
load $ZSH/oh-my-zsh.sh;
load $HOME/.exports;
load $HOME/.aliases;
load $HOME/.sman/sman.rc;

# # AUTOCOMPLETE
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)

# BINDINGS
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
# bindkey -v '^?' backward-delete-char
bindkey -M vicmd v edit-command-line
bindkey -s '^o' 'cdranger^M'  # zsh

# ALIASES
#alias -s pdf="open"
#alias -s {jpg,JPG,jpeg,JPEG,png,PNG,gif,GIF}="open"
#alias -s {mp3,ogg,wav,flac}="open"
#alias -s {mpg,mpeg,avi,ogm,wmv,m4v,mp4,mov}="open"

alias -s {txt}="vim"
alias -g ...="../.."
alias -g ALL="print -C 1 **/**"
alias -g DO="| xargs -n1 "
alias -g G="| egrep -i"
alias -g GI="| egrep -iv"
alias -g L="| less"
alias -g M="| more"
alias -g S="| sort"
alias -g NOCOLOR='|sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"'

# OPTIONS
setopt always_to_end
setopt auto_resume
setopt autocd
setopt complete_in_word
setopt extended_history
setopt extendedglob
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt inc_append_history
setopt listpacked
# setopt no_always_last_prompt
setopt nobeep
setopt prompt_cr
setopt share_history
setopt short_loops
setopt prompt_subst

# FUNCTIONS
gt() { grep --color=always -n -Rs $2 $1 . }
gtf() { grep -Rl $2 $1 . }
h() { cat $HISTFILE | grep $1 }
dps() {ssh -o "StrictHostKeyChecking no" lukaszmalik@$1 "sudo docker ps"; }
corobia() {
    for i in `find . -mindepth 1 -maxdepth 1 -type d `; do;
        echo $i;
        cd $i
        git --no-pager my --before=$1 --after=$2 | sort
        cd - &>/dev/null
    done;
}
cdranger () {
    tmp="$(mktemp)"; ranger --choosedir="$tmp" "$@";
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"; rm -f "$tmp";
        if [ -d "$dir" ]; then; if [ "$dir" != "$(pwd)" ]; then; cd "$dir"; fi; fi;
    fi
}

# LOAD THIS LAST
load /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
