config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_aliases:
    src: aliases
    dst: ~/.aliases
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_exports:
    src: exports
    dst: ~/.exports
  f_vagrantfile:
    src: vagrant/debian-jessie-libvirt/Vagrantfile
    dst: ~/.vagrant/debian-jessie-libvirt/Vagrantfile
  f_my.cnf:
    src: my.cnf
    dst: ~/.my.cnf
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_snippets:
    src: snippets
    dst: ~/.snippets
  f_sman.rc:
    src: sman/sman.rc
    dst: ~/.sman/sman.rc
  f_config:
    src: ssh/config
    dst: ~/.ssh/config
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_ini:
    src: config/mc/ini
    dst: ~/.config/mc/ini
  f_debian-chanda-x_vagrantfile:
    src: vagrant/debian-chanda-x/Vagrantfile
    dst: ~/.vagrant/debian-chanda-x/Vagrantfile
  d_shared:
    src: vagrant/shared
    dst: ~/.vagrant/shared
  d_wallpapers:
    src: wallpapers
    dst: ~/.wallpapers
  f_tint2rc:
    src: config/tint2/tint2rc
    dst: ~/.config/tint2/tint2rc
  d_scripts:
    src: scripts
    dst: ~/.scripts
  f_xmodmap:
    src: Xmodmap
    dst: ~/.Xmodmap
  f_sxhkdrc:
    src: config/sxhkd/sxhkdrc
    dst: ~/.config/sxhkd/sxhkdrc
profiles:
  MacBook-Pro-ukasz.local:
    include:
    - debian
    dotfiles:
    - f_vagrantfile
    - f_debian-chanda-x_vagrantfile
  debian:
    dotfiles:
    - d_snippets
    - d_wallpapers
    - f_aliases
    - f_bashrc
    - f_config
    - f_exports
    - f_gitconfig
    - f_ini
    - f_my.cnf
    - f_sman.rc
    - f_tint2rc
    - f_tmux.conf
    - f_vimrc
    - f_xresources
    - f_zshrc
    - d_scripts
    - f_xmodmap
    - f_sxhkdrc
  debian-chanda-openbox:
    include:
    - debian
  debian-chanda:
    include:
    - debian
  pop-os:
    include:
    - debian
    dotfiles:
    - f_vagrantfile
    - f_debian-chanda-x_vagrantfile
