config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_aliases:
    src: aliases
    dst: ~/.aliases
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_exports:
    src: exports
    dst: ~/.exports
  f_vagrantfile:
    src: vagrant/debian-jessie-libvirt/Vagrantfile
    dst: ~/.vagrant/debian-jessie-libvirt/Vagrantfile
  f_my.cnf:
    src: my.cnf
    dst: ~/.my.cnf
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
profiles:
  debian:
    dotfiles:
    - f_aliases
    - f_bashrc
    - f_exports
  debian-chanda:
    include:
    - debian
  pop-os:
    include:
    - debian
    dotfiles:
    - f_vagrantfile
    - f_my.cnf
    - f_gitconfig
    - f_tmux.conf
